apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-medusa
  labels:
    app.kubernetes.io/name: medusa
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: arrakis
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: medusa
    app.kubernetes.io/instance: {{ .Release.Name }}
